{
  __meta__: {
    author: 'rosielowther',
    source: 'https://github.com/enkidevs/curriculum/blob/master/javascript/core/errors/catch-is-block-scoped.md',
  },
  type: 'choose_sequence',
  lang: 'en',
  tags: [
    'enki',
    'caveats',
    'workout',
    'deep',
    'obscura',
  ],
  card: {
    question: '<p>What scope is the catch clause of a try/catch statement in? ???</p>\n',
    answers: [
      {
        text: 'block scoped.',
      },
      {
        text: 'function scoped.',
      },
    ],
    comment: '<p>The <code>catch</code> clause of a <code>try...catch</code> statement is <strong>block</strong> scoped. This is different to the rest of JavaScript which is <strong>function</strong> scoped.  </p>\n<pre><code>try {\n  // ...\n}\ncatch (err) {\n   // err is block scoped\n}\n</code></pre>\n<p>Many linters fail to recognise that it is valid to have multiple  <code>try...catch</code> statements in the same scope, all using <code>err</code>, without it being a repeated variable declaration.</p>\n',
  },
}